services:
  - type: web
    name: fastapi-demo
    env: python
    region: oregon
    plan: free
    rootDir: src/fastapi_demo
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
